### ISSUE TITLE
有一个BUG

### ISSUE THREAD

**Issue by martjay** [QiKe-007/Novel-Audio-Downloader#1]
很多重复名字的文字会被跳过下载

比如说这个：21266

能不能让它按顺序下载然后自动123456这样重命名文件呢

**Comment by martjay** [comment]
而且也只能下载第一页，输入总下载页好像是无效的

**Comment by QiKe-007** [comment]
> 而且也只能下载第一页，输入总下载页好像是无效的

修复BUG
下载逻辑问题：原始代码存在一个逻辑问题，用户在输入总页数和起始页数后，调用 download_novel 函数时只会下载一次页面而不进行循环下载，导致下载过程在完成一个页面后就停止。
*没能及时查收您的回复，表示抱歉

**Comment by QiKe-007** [comment]
> 很多重复名字的文字会被跳过下载
> 
> 比如说这个：21266
> 
> 能不能让它按顺序下载然后自动123456这样重命名文件呢

脚本会自动下载指定专辑的音频，并保存到名为 "Novel audio" 的文件夹下的专辑ID子文件夹 "ID_XXXXX"
